/bin/bash: /sw/ubuntu-22.04/anaconda3/current/lib/libtinfo.so.6: no version information available (required by /bin/bash)
/u/hbt9su/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/u/hbt9su/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/u/hbt9su/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/u/hbt9su/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/u/hbt9su/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/u/hbt9su/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/u/hbt9su/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/u/hbt9su/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/u/hbt9su/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/u/hbt9su/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/u/hbt9su/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/u/hbt9su/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Half-Cheetah-RM1-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Half-Cheetah-RM2-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-M0-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-M1-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-M2-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-M3-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-M4-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-M5-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-M6-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-M7-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-M8-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-M9-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-M10-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-single-M0-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-single-M1-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-single-M2-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-single-M3-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-single-M4-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-single-M5-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-single-M6-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-single-M7-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-single-M8-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-single-M9-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Water-single-M10-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Office-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Office-single-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-M0-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-M1-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-M2-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-M3-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-M4-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-M5-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-M6-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-M7-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-M8-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-M9-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-M10-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-single-M0-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-single-M1-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-single-M2-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-single-M3-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-single-M4-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-single-M5-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-single-M6-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-single-M7-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-single-M8-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-single-M9-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Craft-single-M10-v0[0m
  logger.warn("Overriding environment {}".format(id))
/u/hbt9su/.local/lib/python3.6/site-packages/gym/envs/registration.py:216: UserWarning: [33mWARN: Overriding environment Taxi-v0[0m
  logger.warn("Overriding environment {}".format(id))
WARNING:tensorflow:From /u/hbt9su/baselines/baselines/common/tf_util.py:53: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

WARNING:tensorflow:From /u/hbt9su/baselines/baselines/common/tf_util.py:63: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /u/hbt9su/baselines/baselines/common/tf_util.py:70: The name tf.InteractiveSession is deprecated. Please use tf.compat.v1.InteractiveSession instead.

2024-01-24 11:05:34.306464: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2024-01-24 11:05:34.343321: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2024-01-24 11:05:34.495903: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f178e2e0b0 executing computations on platform CUDA. Devices:
2024-01-24 11:05:34.495946: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): NVIDIA RTX A4500, Compute Capability 8.6
2024-01-24 11:05:34.662524: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2000000000 Hz
2024-01-24 11:05:34.662876: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55f178fbb010 executing computations on platform Host. Devices:
2024-01-24 11:05:34.662902: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2024-01-24 11:05:34.663876: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: NVIDIA RTX A4500 major: 8 minor: 6 memoryClockRate(GHz): 1.65
pciBusID: 0000:03:00.0
2024-01-24 11:05:34.667988: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /u/hbt9su/.local/lib/python3.6/site-packages/cv2/../../lib64:/sw/ubuntu-22.04/cudnn/8.1.0/lib:/sw/ubuntu-22.04/cuda/current/extras/CUPTI/lib64:/sw/ubuntu-22.04/cuda/current/lib64:/sw/ubuntu-22.04/anaconda3/current/lib::/usr/lib/nvidia:/u/hbt9su/.mujoco/mujoco210/bin:/usr/lib/nvidia:/u/hbt9su/.mujoco/mujoco210/bin
2024-01-24 11:05:34.669808: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /u/hbt9su/.local/lib/python3.6/site-packages/cv2/../../lib64:/sw/ubuntu-22.04/cudnn/8.1.0/lib:/sw/ubuntu-22.04/cuda/current/extras/CUPTI/lib64:/sw/ubuntu-22.04/cuda/current/lib64:/sw/ubuntu-22.04/anaconda3/current/lib::/usr/lib/nvidia:/u/hbt9su/.mujoco/mujoco210/bin:/usr/lib/nvidia:/u/hbt9su/.mujoco/mujoco210/bin
2024-01-24 11:05:34.671759: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /u/hbt9su/.local/lib/python3.6/site-packages/cv2/../../lib64:/sw/ubuntu-22.04/cudnn/8.1.0/lib:/sw/ubuntu-22.04/cuda/current/extras/CUPTI/lib64:/sw/ubuntu-22.04/cuda/current/lib64:/sw/ubuntu-22.04/anaconda3/current/lib::/usr/lib/nvidia:/u/hbt9su/.mujoco/mujoco210/bin:/usr/lib/nvidia:/u/hbt9su/.mujoco/mujoco210/bin
2024-01-24 11:05:34.673672: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /u/hbt9su/.local/lib/python3.6/site-packages/cv2/../../lib64:/sw/ubuntu-22.04/cudnn/8.1.0/lib:/sw/ubuntu-22.04/cuda/current/extras/CUPTI/lib64:/sw/ubuntu-22.04/cuda/current/lib64:/sw/ubuntu-22.04/anaconda3/current/lib::/usr/lib/nvidia:/u/hbt9su/.mujoco/mujoco210/bin:/usr/lib/nvidia:/u/hbt9su/.mujoco/mujoco210/bin
2024-01-24 11:05:34.675567: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /u/hbt9su/.local/lib/python3.6/site-packages/cv2/../../lib64:/sw/ubuntu-22.04/cudnn/8.1.0/lib:/sw/ubuntu-22.04/cuda/current/extras/CUPTI/lib64:/sw/ubuntu-22.04/cuda/current/lib64:/sw/ubuntu-22.04/anaconda3/current/lib::/usr/lib/nvidia:/u/hbt9su/.mujoco/mujoco210/bin:/usr/lib/nvidia:/u/hbt9su/.mujoco/mujoco210/bin
2024-01-24 11:05:34.677317: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /u/hbt9su/.local/lib/python3.6/site-packages/cv2/../../lib64:/sw/ubuntu-22.04/cudnn/8.1.0/lib:/sw/ubuntu-22.04/cuda/current/extras/CUPTI/lib64:/sw/ubuntu-22.04/cuda/current/lib64:/sw/ubuntu-22.04/anaconda3/current/lib::/usr/lib/nvidia:/u/hbt9su/.mujoco/mujoco210/bin:/usr/lib/nvidia:/u/hbt9su/.mujoco/mujoco210/bin
2024-01-24 11:05:36.833122: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2024-01-24 11:05:36.833194: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
2024-01-24 11:05:36.833222: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-01-24 11:05:36.833232: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2024-01-24 11:05:36.833240: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
WARNING:tensorflow:From /u/hbt9su/baselines/baselines/common/misc_util.py:58: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

WARNING:tensorflow:From /u/hbt9su/PartialSatLTL/psltl/baseline_algo/crm/rl_agents/dhrm/controller.py:84: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From /u/hbt9su/PartialSatLTL/psltl/baseline_algo/crm/rl_agents/dhrm/build_graph.py:130: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /u/hbt9su/baselines/baselines/common/input.py:57: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
WARNING:tensorflow:From /u/hbt9su/baselines/baselines/common/models.py:94: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e7e4f940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e7e4f940>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e7e4ff28>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e7e4ff28>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e77f9dd8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e77f9dd8>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e77f9dd8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e77f9dd8>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e7e4fb38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e7e4fb38>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e7e4fb38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e7e4fb38>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:From /u/hbt9su/PartialSatLTL/psltl/baseline_algo/crm/rl_agents/dhrm/build_graph.py:145: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e76e2f98>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e76e2f98>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e76f0898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e76f0898>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e776bd30>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e776bd30>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e776bd30>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e776bd30>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e776b898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e776b898>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e776bba8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e776bba8>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e7e4f588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e7e4f588>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e768d9b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e768d9b0>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e769a208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e769a208>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e769a208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e769a208>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e76944e0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e76944e0>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e769a2e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e769a2e8>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e7736828>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e7736828>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e7672860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e7672860>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e76b9dd8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e76b9dd8>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e76b9dd8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e76b9dd8>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e76b95f8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e76b95f8>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e76b95f8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e76b95f8>>: AttributeError: module 'gast' has no attribute 'Index'
2024-01-24 11:05:38.099225: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e6bd2c88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e6bd2c88>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e6bf6748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e6bf6748>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6be4780>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6be4780>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6be4780>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6be4780>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6be46d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6be46d8>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6be46d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6be46d8>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e6f28d30>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e6f28d30>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e6af31d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e6af31d0>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6af3940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6af3940>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6af3940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6af3940>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6af3898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6af3898>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6af3898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6af3898>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e6f28ac8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e6f28ac8>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e6af3898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e6af3898>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6afb8d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6afb8d0>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6afb8d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6afb8d0>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6a82390>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6a82390>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6b99400>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6b99400>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e6b8de80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e6b8de80>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e6a95518>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7fc9e6a95518>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6532710>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6532710>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6532710>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6532710>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e64cb5f8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e64cb5f8>>: AttributeError: module 'gast' has no attribute 'Index'
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6ab3fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fc9e6ab3fd0>>: AttributeError: module 'gast' has no attribute 'Index'
/var/spool/slurmd/job2857907/slurm_script: line 55: 3649741 CPU time limit exceeded (core dumped) python run.py --alg ${env_name} --env ${env} --num_timesteps ${timesteps} --gamma ${gamma} --env_name ${env_name} --seed ${seed} --use_rs
